<a href="https://colab.research.google.com/github/MichalBenYaish/RepositiryLearn/blob/main/24_11_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Labs


In [ ]:
import numpy as np
import pylab as plt
%matplotlib inline

Create an array of 10 zeros


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create an array of 10 ones

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Create an array of 10 fives

In [ ]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Create an array of the integers from 10 to 50

In [ ]:
 np.arange(10,51,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Create an array of all the even integers from 10 to 50

In [ ]:
np.arange(10,51,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.random.random_integers(0,8,(3,3))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 8 + 1) instead
  """Entry point for launching an IPython kernel.


array([[7, 4, 6],
       [0, 3, 2],
       [4, 6, 4]])

Create a 3x3 identity matrix

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Use NumPy to generate a random number between 0 and 1

In [ ]:
np.random.normal(0,1,1)

array([2.12905819])

Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
np.random.standard_normal(25)

array([-0.88476378, -0.61419753, -0.51083594, -0.07311567, -0.27674182,
        0.65644287, -2.21827889, -0.7138274 , -0.60964653,  0.69638046,
       -0.08856237, -0.03466848, -0.70669954,  0.23838916,  0.12269055,
        0.93675088,  0.32710852, -0.21129883,  1.47616337, -1.12422878,
        0.20164405,  1.99211749, -0.59211454, -0.61179528, -0.47412454])

Create the following matrix

In [ ]:
np.arange(0.01,1,0.01)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])

Create an array of 20 linearly spaced points between 0 and 1

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Write a function that takes as input a 2-D ndarray and scales the last row and column by 2

In [ ]:
def scale(A):
  A[-1, :] *= 2
  A[:, -1]*=2

M = np.array([[1, 2], [3, 4]])
scale(M)
print (M)

 

 


[[ 1  4]
 [ 6 16]]


Create a numpy array with 100 numbers from 1 to 20. You are not allowed to use any loop

In [ ]:
b=np.linspace(1,20,100)
b

array([ 1.        ,  1.19191919,  1.38383838,  1.57575758,  1.76767677,
        1.95959596,  2.15151515,  2.34343434,  2.53535354,  2.72727273,
        2.91919192,  3.11111111,  3.3030303 ,  3.49494949,  3.68686869,
        3.87878788,  4.07070707,  4.26262626,  4.45454545,  4.64646465,
        4.83838384,  5.03030303,  5.22222222,  5.41414141,  5.60606061,
        5.7979798 ,  5.98989899,  6.18181818,  6.37373737,  6.56565657,
        6.75757576,  6.94949495,  7.14141414,  7.33333333,  7.52525253,
        7.71717172,  7.90909091,  8.1010101 ,  8.29292929,  8.48484848,
        8.67676768,  8.86868687,  9.06060606,  9.25252525,  9.44444444,
        9.63636364,  9.82828283, 10.02020202, 10.21212121, 10.4040404 ,
       10.5959596 , 10.78787879, 10.97979798, 11.17171717, 11.36363636,
       11.55555556, 11.74747475, 11.93939394, 12.13131313, 12.32323232,
       12.51515152, 12.70707071, 12.8989899 , 13.09090909, 13.28282828,
       13.47474747, 13.66666667, 13.85858586, 14.05050505, 14.24

Create a numpy array containing the sine of the numbers from the above array. 

In [ ]:
np.sin(b)

array([ 0.84147098,  0.92908054,  0.98257421,  0.99998769,  0.98068157,
        0.92536476,  0.8360685 ,  0.71607176,  0.56978082,  0.40256749,
        0.22057186,  0.03047682, -0.16073733, -0.34604919, -0.51865411,
       -0.67221402, -0.8010902 , -0.90055029, -0.96694212, -0.99782778,
       -0.99207314, -0.94988952, -0.8728259 , -0.76371206, -0.62655467,
       -0.46639016, -0.28909977, -0.10119362,  0.09042837,  0.27872982,
        0.45679629,  0.61808918,  0.7566858 ,  0.86749687,  0.9464534 ,
        0.99065611,  0.99848187,  0.96964331,  0.9051994 ,  0.8075165 ,
        0.68018156,  0.52787031,  0.35617562,  0.17140215, -0.01966522,
       -0.21001048, -0.39264414, -0.56085989, -0.70848083, -0.83008631,
       -0.92121097, -0.97850871, -0.99987556, -0.98452691, -0.93302638,
       -0.84726506, -0.73039212, -0.58669914, -0.42146253, -0.24074979,
       -0.05119671,  0.14023632,  0.32651987,  0.50081358,  0.6567174 ,
        0.78850651,  0.89134161,  0.9614466 ,  0.99624721,  0.99

Compute the dot product of arrays [1,2,3,4] and [cos(1),cos(2), cos(3)], but first you have to reshape them into  2-dimensional arrays


In [ ]:
v = np.arange(1,5)
v.shape = (4,1)
print(v)
t=np.cos(np.arange(1,4))
t.shape = (1,3)
print(t)
np.dot(v,t)

[[1]
 [2]
 [3]
 [4]]
[[ 0.54030231 -0.41614684 -0.9899925 ]]


array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [ 1.08060461, -0.83229367, -1.97998499],
       [ 1.62090692, -1.24844051, -2.96997749],
       [ 2.16120922, -1.66458735, -3.95996999]])

Create two numpy arrays (3,3)  - A, B


In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[12,32,23],[54,25,76],[17,78,39]])

compute A + B

In [ ]:
A+B

array([[13, 34, 26],
       [58, 30, 82],
       [24, 86, 48]])

compute 3A + B

In [ ]:
3*A + B

array([[ 15,  38,  32],
       [ 66,  40,  94],
       [ 38, 102,  66]])

Find the maximum and the minimum of B

In [ ]:
print(np.max(B))
np.min(B)

78


12

Normalize the matrix B by adding a constant c that makes its minimum be equal to 0

In [ ]:
yy = B-np.min(B)

print(yy)


[[ 0 20 11]
 [42 13 64]
 [ 5 66 27]]


array([[   0, 1080,  187],
       [1344,  325, 4992],
       [ 115, 5016, 1053]])

Compute the sum of the elements in A

In [ ]:
A.sum()

45

Compute the transpose of A

In [ ]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Compute the inverse of A. Use numpy.linalg

In [ ]:
np.linalg.inv([[1,-1,-2],
               [2,-3,-5],
               [-1,3,5]])

array([[-4.4408921e-16,  1.0000000e+00,  1.0000000e+00],
       [ 5.0000000e+00, -3.0000000e+00, -1.0000000e+00],
       [-3.0000000e+00,  2.0000000e+00,  1.0000000e+00]])

Compute the determinant of A

In [ ]:
np.linalg.det(A)

0.0

Solve the following equations:<br>
    X  + 2Y = 3<br/>
    3X + 4Y = 0

In [ ]:


np.linalg.solve(np.array([[1,2],[3,4]]),np.array([3,0]))

array([-6. ,  4.5])