<a href="https://colab.research.google.com/github/MichalBenYaish/RepositiryLearn/blob/main/Numpy_Lab1_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Labs


In [ ]:
import numpy as np
import pylab
%matplotlib inline

Create an array of 10 zeros


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create an array of 10 ones

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Create an array of 10 fives

In [ ]:
np.ones(10)*5


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Create an array of the integers from 10 to 50

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Create an array of all the even integers from 10 to 50

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3x3 identity matrix

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Use NumPy to generate a random number between 0 and 1

In [ ]:
np.random.rand(1)

array([0.51398167])

Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
np.random.randn(25)

array([ 0.13831914,  1.28615575,  1.01921511, -0.47402982,  0.64456789,
        0.75742207, -1.39608963, -1.13812427, -1.50923374,  2.26765328,
        0.55070679, -1.87854806,  1.01662293,  0.5178121 , -0.77210984,
       -1.63752378, -0.58668157, -0.71608423, -0.42375242, -1.04515325,
       -1.53238458,  1.18994788,  0.77490136,  1.06743755,  0.26112235])

Create the following matrix

In [ ]:
np.arange(1,101).reshape(10,10) / 100.0

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

Create an array of 20 linearly spaced points between 0 and 1

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Write a function that takes as input a 2-D ndarray and scales the last row and column by 2

In [ ]:
def scale(A):
    A[-1, :] *= 2
    A[:, -1] *= 2

M = np.array([[1, 2], [3, 4]])
scale(M)
print (M)

[[ 1  4]
 [ 6 16]]


Create a numpy array with 100 numbers from 1 to 20. You are not allowed to use any loop

In [ ]:
b=np.linspace(1,20,100)

Create a numpy array containing the sine of the numbers from the above array. 

In [ ]:
c=np.sin(b)

Compute the dot product of arrays [1,2,3,4] and [cos(1),cos(2), cos(3)], but first you have to reshape them into  2-dimensional arrays


In [ ]:
v = np.arange(1,5)
v.shape = (4,1)
t = np.cos(np.arange(1,4))
t.shape = (1,3)
m = np.dot(v,t)
print (m)

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [ 1.08060461 -0.83229367 -1.97998499]
 [ 1.62090692 -1.24844051 -2.96997749]
 [ 2.16120922 -1.66458735 -3.95996999]]


Create two numpy arrays (3,3)  - A, B


In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[12,32,23],[54,25,76],[17,78,39]])


compute A + B

In [ ]:
A+B

array([[13, 34, 26],
       [58, 30, 82],
       [24, 86, 48]])

compute 3A + B

In [ ]:
A*3 + B

array([[ 15,  38,  32],
       [ 66,  40,  94],
       [ 38, 102,  66]])

Find the maximum and the minimum of B

In [ ]:
print (np.min(B))
print (np.max(B))

12
78


Normalize the matrix B by adding a constant c that makes its minimum be equal to 0

In [ ]:
B-np.min(B)

array([[ 0, 20, 11],
       [42, 13, 64],
       [ 5, 66, 27]])

Compute the sum of the elements in A

In [ ]:
A.sum()

45

Compute the transpose of A

In [ ]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Compute the inverse of A. Use numpy.linalg

In [ ]:
np.linalg.inv(A)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

Compute the determinant of A

In [ ]:
np.linalg.det(A)

6.66133814775094e-16

Solve the following equations:
    X  + 2Y = 3
    3X + 4Y = 0

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([3,0])
print (np.linalg.solve(A,B))

[-6.   4.5]
